import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../utils/shell', () => ({
  execCommand: vi.fn(),
  isCommandAvailable: vi.fn(),
}));
vi.mock('../utils/fileSystem', () => ({
  getWorkspaceRoot: vi.fn(() => '/workspace'),
  readWorkspaceFile: vi.fn(),
  writeWorkspaceFile: vi.fn(),
  listFiles: vi.fn(),
}));

import { execCommand, isCommandAvailable } from '../utils/shell';
import { readWorkspaceFile, writeWorkspaceFile, listFiles } from '../utils/fileSystem';
import { buildPrBody, createPullRequest, isPrCliAvailable, linkPrToExecution } from './prCreator';
import type { PrOptions } from './prCreator';

const mockExec = execCommand as ReturnType<typeof vi.fn>;
const mockAvailable = isCommandAvailable as ReturnType<typeof vi.fn>;
const mockReadFile = readWorkspaceFile as ReturnType<typeof vi.fn>;
const mockWriteFile = writeWorkspaceFile as ReturnType<typeof vi.fn>;
const mockListFiles = listFiles as ReturnType<typeof vi.fn>;

const sampleOptions: PrOptions = {
  specId: 'SDD-036',
  title: 'Implement GitHub PR creator',
  context: 'Creates pull requests using the gh CLI.',
  requirements: [
    'createPullRequest must call gh pr create',
    'isPrCliAvailable must check gh auth',
  ],
  executionSummary: 'Tokens: 1000 in / 500 out. Duration: 30s. Tests: passed.',
  branchName: 'sdd/SDD-036-pr-creator',
};

beforeEach(() => vi.clearAllMocks());

describe('buildPrBody', () => {
  it('includes spec ID section', () => {
    expect(buildPrBody(sampleOptions)).toContain('## Spec: SDD-036');
  });

  it('includes context text', () => {
    expect(buildPrBody(sampleOptions)).toContain('Creates pull requests using the gh CLI.');
  });

  it('formats requirements as a bullet list', () => {
    const body = buildPrBody(sampleOptions);
    expect(body).toContain('- createPullRequest must call gh pr create');
    expect(body).toContain('- isPrCliAvailable must check gh auth');
  });

  it('includes execution summary section', () => {
    const body = buildPrBody(sampleOptions);
    expect(body).toContain('## Execution Summary');
    expect(body).toContain('Tokens: 1000 in / 500 out');
  });

  it('ends with SDD Platform footer', () => {
    expect(buildPrBody(sampleOptions)).toContain('Generated by SDD Platform');
  });
});

describe('createPullRequest', () => {
  it('returns error when gh CLI is not installed', async () => {
    mockAvailable.mockResolvedValueOnce(false);
    const result = await createPullRequest(sampleOptions);
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/not installed/i);
  });

  it('returns error when gh is not authenticated', async () => {
    mockAvailable.mockResolvedValueOnce(true);
    mockExec.mockResolvedValueOnce({
      success: false,
      stdout: '',
      stderr: 'You are not logged into any GitHub hosts.',
    });
    const result = await createPullRequest(sampleOptions);
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/gh auth login/i);
  });

  it('returns PR URL on success', async () => {
    mockAvailable.mockResolvedValueOnce(true);
    mockExec
      .mockResolvedValueOnce({ success: true, stdout: '', stderr: '' }) // auth check
      .mockResolvedValueOnce({
        success: true,
        stdout: 'https://github.com/owner/repo/pull/42',
        stderr: '',
      });
    const result = await createPullRequest(sampleOptions);
    expect(result.success).toBe(true);
    expect(result.url).toBe('https://github.com/owner/repo/pull/42');
  });

  it('returns error when gh pr create fails', async () => {
    mockAvailable.mockResolvedValueOnce(true);
    mockExec
      .mockResolvedValueOnce({ success: true, stdout: '', stderr: '' })
      .mockResolvedValueOnce({ success: false, stdout: '', stderr: 'No commits on branch.' });
    const result = await createPullRequest(sampleOptions);
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/No commits/);
  });
});

describe('isPrCliAvailable', () => {
  it('returns false when gh is not installed', async () => {
    mockAvailable.mockResolvedValueOnce(false);
    expect(await isPrCliAvailable()).toBe(false);
  });

  it('returns false when gh is installed but not authenticated', async () => {
    mockAvailable.mockResolvedValueOnce(true);
    mockExec.mockResolvedValueOnce({ success: false, stdout: '', stderr: 'not logged in' });
    expect(await isPrCliAvailable()).toBe(false);
  });

  it('returns true when gh is installed and authenticated', async () => {
    mockAvailable.mockResolvedValueOnce(true);
    mockExec.mockResolvedValueOnce({ success: true, stdout: 'Logged in to github.com', stderr: '' });
    expect(await isPrCliAvailable()).toBe(true);
  });
});

describe('linkPrToExecution', () => {
  it('updates prUrl in the latest execution record', async () => {
    const record = { specId: 'SDD-036', prUrl: null, executionNumber: 1 };
    mockListFiles.mockResolvedValueOnce(['.sdd/executions/SDD-036/exec-001.json']);
    mockReadFile.mockResolvedValueOnce(JSON.stringify(record));
    mockWriteFile.mockResolvedValueOnce(undefined);

    await linkPrToExecution('SDD-036', 'https://github.com/owner/repo/pull/42');

    expect(mockWriteFile).toHaveBeenCalledWith(
      '.sdd/executions/SDD-036/exec-001.json',
      expect.stringContaining('"prUrl": "https://github.com/owner/repo/pull/42"'),
    );
  });

  it('does nothing when no execution records exist', async () => {
    mockListFiles.mockResolvedValueOnce([]);
    await linkPrToExecution('SDD-036', 'https://github.com/owner/repo/pull/42');
    expect(mockWriteFile).not.toHaveBeenCalled();
  });
});
