import { execCommand, isCommandAvailable } from '../utils/shell';
import { getWorkspaceRoot, readWorkspaceFile, writeWorkspaceFile, listFiles } from '../utils/fileSystem';
import { EXECUTIONS_FOLDER } from '../utils/constants';

export type PrOptions = {
  specId: string;
  title: string;
  context: string;
  requirements: string[];
  executionSummary: string;
  branchName: string;
};

export type PrResult = { success: boolean; url?: string; error?: string };

export async function isPrCliAvailable(): Promise<boolean> {
  if (!(await isCommandAvailable('gh'))) return false;
  const cwd = getWorkspaceRoot();
  const result = await execCommand('gh auth status', { cwd });
  return result.success;
}

export async function createPullRequest(options: PrOptions): Promise<PrResult> {
  const cwd = getWorkspaceRoot();

  if (!(await isCommandAvailable('gh'))) {
    return {
      success: false,
      error:
        'gh CLI is not installed. Install it from https://cli.github.com and run "gh auth login".',
    };
  }

  const authCheck = await execCommand('gh auth status', { cwd });
  if (!authCheck.success) {
    return {
      success: false,
      error: 'gh CLI is not authenticated. Run "gh auth login" to authenticate.',
    };
  }

  const body = buildPrBody(options);
  const title = `feat: ${options.title} (${options.specId})`;

  // Pass title and body via env vars to avoid shell escaping issues with multi-line content
  const result = await execCommand(
    `gh pr create --title "$GH_PR_TITLE" --body "$GH_PR_BODY" --head "${options.branchName}"`,
    { cwd, env: { GH_PR_TITLE: title, GH_PR_BODY: body } },
  );

  if (!result.success) {
    return { success: false, error: result.stderr.trim() || 'PR creation failed.' };
  }

  // gh pr create outputs the PR URL on success
  return { success: true, url: result.stdout.trim() };
}

export function buildPrBody(options: PrOptions): string {
  const reqList = options.requirements.map((r) => `- ${r}`).join('\n');
  return [
    `## Spec: ${options.specId}`,
    options.context,
    '',
    '## Requirements',
    reqList,
    '',
    '## Execution Summary',
    options.executionSummary,
    '',
    '---',
    'Generated by SDD Platform',
  ].join('\n');
}

export async function linkPrToExecution(specId: string, prUrl: string): Promise<void> {
  const pattern = `${EXECUTIONS_FOLDER}/${specId}/exec-*.json`;
  const files = await listFiles(pattern);
  if (files.length === 0) return;

  const latest = files.sort().at(-1)!;
  const content = await readWorkspaceFile(latest);
  if (!content) return;

  let record: Record<string, unknown>;
  try {
    record = JSON.parse(content) as Record<string, unknown>;
  } catch {
    return;
  }

  record.prUrl = prUrl;
  await writeWorkspaceFile(latest, JSON.stringify(record, null, 2));
}
