/**
 * Input source for requirements text.
 */
export interface RequirementsInput {
  rawText: string;
  source: 'freetext' | 'file' | 'clipboard';
}

/**
 * A single spec file generated by the SDD Planner.
 */
export interface GeneratedSpec {
  /** The spec ID, e.g. "SDD-042" */
  specId: string;
  /** URL-safe slug for the file name, e.g. "add-user-auth" */
  slug: string;
  /** Raw .sdd.md file content */
  content: string;
}

/**
 * Input to the SDD Planner agent describing what needs to be planned.
 */
export interface PlanningRequest {
  /** Free-text description of what the builder wants to build */
  requirements: string;
  /** Spec IDs already present in the project, used to avoid duplication */
  existingSpecIds: string[];
  /** Project ID prefix, e.g. "SDD" */
  projectPrefix: string;
  /** Optional coding conventions or style guide text to inject */
  conventions?: string;
  /** Optional directory tree of the repository for context */
  repoTree?: string;
  /** Optional feedback from a previous planning attempt to refine output */
  feedback?: string;
}

/**
 * Result returned by the SDD Planner agent after attempting to generate specs.
 */
export type PlanningResult =
  | { success: true; specs: GeneratedSpec[] }
  | { success: false; error: string };
